pipeline {

  agent any

  tools {
    maven "mavenlocal"
  }
  stages {
    stage('Stage 1 - Checkout Code') {
      steps {
        //Get the code form GITHUB							
        git branch: 'main', changelog: false, poll: false, url: 'https://github.com/JasonkDaniel/jenkindemo4.git'
      }
    }
    stage('Stage 2 - Compile Code') {
      steps {
        //cmd to compile the code
        bat "cd jenkins-springboot-test"
        bat "mvn -f jenkins-springboot-test\\pom.xml clean install"
        //sh "mvn compile"
      }
    }
    stage('Stage 3 - Run Unit Tests') {
      steps {
        //cmd to run tests							
        bat "mvn -f jenkins-springboot-test\\pom.xml test"
      }
    }
    stage('Stage 4 -Create build') {
      steps {
        //cmd to create the build of project							
        bat "mvn -f jenkins-springboot-test\\pom.xml package"
      }
    }

  }
  post {
    failure {
      //Send email to team about the failure
      //emailext body: 'Jenkins build failed', subject: 'Jenkins build failed', to: 'test1@test.com'

      echo "Email sent for Jenkins build failed"
    }
  }

}
